baseURL = "http://web-verse.ru"
title = "NEOPIXEL"
logo_image = "/images/NEOPIXEL_LOGO.png"
use_logo_instead_of_title = true
languageCode = "ru"
theme = "blowfish"


[params]
  colorScheme = "gray"
  defaultAppearance = "dark"
  autoSwitchAppearance = false
  showScrollToTop = true

[params.brand]
    logo = "site/img/NEOPIXEL_LOGO.png"

[params.header]
   showLogo = true
   showTitle = false # Чтобы текст "NEOPIXEL" не накладывался на картинку
[[menus.main]]
  name = "О проекте"
  url = "/about/"
  weight = 10

[[menus.main]]
  name = "Компоненты"
  url = "/components/"
  weight = 20

[[menus.main]]
    name = "Журнал"
    url = "/posts/"
    weight = 20

[[menus.main]]
    name = "Ресурсы"
    url = "/resources/"
    weight = 20

[[menus.main]]
    name = "Участники"
    url = "/members/"
    weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

