baseURL = "http://web-verse.ru/site/"
title = "NEOPIXEL"
languageCode = "ru"
theme = "blowfish"


[params]
  colorScheme = "gray"
  defaultAppearance = "dark"
  autoSwitchAppearance = false
  showScrollToTop = true


[[menus.main]]
  name = "О проекте"
  url = "/about/"
  weight = 10

[[menus.main]]
  name = "Компоненты"
  url = "/components/"
  weight = 20

[[menus.main]]
    name = "Журнал"
    url = "/posts/"
    weight = 20

[[menus.main]]
    name = "Ресурсы"
    url = "/resources/"
    weight = 20

[[menus.main]]
    name = "Участники"
    url = "/members/"
    weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

